import HomeChild from "./components/HomeChild";
import { logger } from "@/server/index";

export default function Home() {
  logger.info({
    message: "Home Page",
    data: { id: 123123, desc: "GET" },
  });
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold">Home Page1</h1>
      <p className="text-xl">Generated by create next app</p>
      <HomeChild />
    </main>
  );
}
