import HomeChild from "./components/HomeChild";
import { Logger } from "@/server/index";

Logger.info("Home Page", { page_name: "/home" });
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold">Home Page1</h1>
      <p className="text-xl">Generated by create next app</p>
      <HomeChild />
    </main>
  );
}
